// 카테고리
export const AMENITY_CATEGORY = {
  BASIC: 'BASIC',
  ELECTRONICS: 'ELECTRONICS',
  FOOD: 'FOOD',
  INTERIOR: 'INTERIOR',
  SERVICES: 'SERVICES',
  CONDITIONS: 'CONDITIONS',
  OPERATION: 'OPERATION',
} as const;

// 서버의 ENUM과 1:1 매칭을 위한 KEY
export const AMENITY = {
  // BASIC
  OUTLET: 'OUTLET',
  AIR_CONDITIONER: 'AIR_CONDITIONER',
  HEATING: 'HEATING',
  WATER_SUPPLY: 'WATER_SUPPLY',
  WATER_PURIFIER: 'WATER_PURIFIER',
  DOOR_LOCK: 'DOOR_LOCK',

  // ELECTRONICS
  TV_PROJECTOR: 'TV_PROJECTOR',
  INTERNET_WIFI: 'INTERNET_WIFI',
  AUDIO_MIC: 'AUDIO_MIC',
  FULL_LENGTH_MIRROR: 'FULL_LENGTH_MIRROR',
  FIRST_AID_KIT: 'FIRST_AID_KIT',
  PRINTER_COPIER: 'PRINTER_COPIER',
  WHITEBOARD: 'WHITEBOARD',
  PC_NOTEBOOK: 'PC_NOTEBOOK',
  FAX: 'FAX',

  // FOOD
  FOOD_ALLOWED: 'FOOD_ALLOWED',
  ALCOHOL_ALLOWED: 'ALCOHOL_ALLOWED',

  // INTERIOR
  CHAIR_TABLE: 'CHAIR_TABLE',
  COMMON_KITCHEN: 'COMMON_KITCHEN',
  COOKING_FACILITY: 'COOKING_FACILITY',
  LOUNGE_WAITING_AREA: 'LOUNGE_WAITING_AREA',
  INNER_RESTROOM: 'INNER_RESTROOM',
  GENDER_SEPARATE_RESTROOM: 'GENDER_SEPARATE_RESTROOM',
  TERRACE_ROOFTOP: 'TERRACE_ROOFTOP',
  BBQ_FACILITY: 'BBQ_FACILITY',
  DRESSING_ROOM: 'DRESSING_ROOM',
  SHOWER_FACILITY: 'SHOWER_FACILITY',
  PERSONAL_LOCKER: 'PERSONAL_LOCKER',

  // SERVICES
  CAFE_RESTAURANT: 'CAFE_RESTAURANT',
  SIMPLE_SNACKS_DRINKS: 'SIMPLE_SNACKS_DRINKS',
  CATERING: 'CATERING',
  MERCHANDISE_SALES: 'MERCHANDISE_SALES',

  // CONDITIONS
  NO_SMOKING: 'NO_SMOKING',
  PARKING: 'PARKING',
  PETS_ALLOWED: 'PETS_ALLOWED',

  // OPERATION
  YEAR_ROUND: 'YEAR_ROUND',
  HOUR_24_OPERATION: 'HOUR_24_OPERATION',
} as const;

export type Amenity = (typeof AMENITY)[keyof typeof AMENITY];
export type AmenityCategory = (typeof AMENITY_CATEGORY)[keyof typeof AMENITY_CATEGORY];
