export const REGIONS = [
  { key: 'Seoul', label: '서울', isActive: true },
  { key: 'Gyeonggi', label: '경기', isActive: false },
  { key: 'Incheon', label: '인천', isActive: false },
  { key: 'Busan', label: '부산', isActive: false },
  { key: 'Gwangju', label: '광주', isActive: false },
  { key: 'Daegu', label: '대구', isActive: false },
  { key: 'Daejeon', label: '대전', isActive: false },
  { key: 'Ulsan', label: '울산', isActive: false },
  { key: 'Jeju', label: '제주', isActive: false },
  { key: 'Gangwon', label: '강원', isActive: false },
  { key: 'Gyeongnam', label: '경남', isActive: false },
  { key: 'Gyeongbuk', label: '경북', isActive: false },
  { key: 'Jeonla', label: '전남/전북', isActive: false },
  { key: 'ChungBuk', label: '충북', isActive: false },
  { key: 'ChungnamAndSejong', label: '충남/세종', isActive: false },
];

export const AREA_FILTERS = {
  SEOUL_ALL: '서울 전체',
  HONGDAE_HAPJEONG_SANGSU_YEONNAM: '홍대·합정·상수·연남',
  GANGNAM_YEOKSAM_SEONLEUNG_SAMSUNG: '강남역·역삼·선릉·삼성',
  SINCHON_EHWA_AHYEON_YEONHUI: '신촌·이대·아현·연희',
  SINSA_NONHYEON_CHEONGDAM_APGUJEONG: '신사·논현·청담·압구정',
  MANGWON_SEONGSAN_SANGAM: '망원·성산·상암',
  SEOCHO_GYODAE_BANGBAE: '서초·교대·방배',
  MYEONGDONG_EULJIRO_DONGDAEMUNSTATION: '명동·을지로·동대문역',
  SEONGSU_WANGSIMNI_SEOULFOREST: '성수·왕십리·서울숲',
  YEONGDEUNGPO_YEOUIDO_DANGSAN_MUNRAE: '영등포·여의도·당산·문래',
  JONGNO_GWANGHWAMUN_DAEHANGNO: '종로·광화문·대학로',
  SONGPA_JAMSIL_BANGI: '송파·잠실·방이',
  YONGSAN_ITAEWON_HANNAM: '용산·이태원·한남',
  GWANAK_SILLIM_SNUSTATION: '관악·신림·서울대입구',
  GWANGJIN_KONKUK_GUUI_GUNJA: '광진·건대·구의·군자',
  DONGJAK_SADANG_ISU: '동작·사당·이수',
  SEONGBUK_SUNGSHIN_ANAM: '성북·성신여대·안암',
  GANGSEO_MAGOK_HWAGOK: '강서·마곡·화곡',
  DOGOK_DAECHI_GAECHE_SUSUEO: '도곡·대치·개포·수서',
  MAPO_GONGDEOK_DAEHEUNG: '마포역·공덕·대흥',
  GURO_SINDORIM_GOCHEOK: '구로·신도림·고척',
  GEUMCHEON_GASAN_DOKSAN: '금천·가산·독산',
  GANGDONG_SEONGNAE_CHEONHO_GILDONG: '강동·성내·천호·길동',
  DONGDAEMUNGU_CHEONGRYANGRI_HOEGI: '동대문구·청량리·회기',
  YANGCHEON_MOKDONG_SINJEONG: '양천·목동·신정',
  EUNPYEONG_BULGWANG_YEONSINNAE: '은평·불광·연신내',
  NOWON_SANGGYE_GONGLEUNG: '노원·상계·공릉',
  GANGBUK_SUYU_MIA: '강북·수유·미아',
  JUNGNANG_SANGBONG_MYEONMOK: '중랑·상봉·면목',
  DOBONG_SSANGMUN_CHANGDONG: '도봉·쌍문·창동',
} as const;

export type AreaKey = keyof typeof AREA_FILTERS;
export type AreaLabel = (typeof AREA_FILTERS)[AreaKey];
