export const AREA_FILTERS = [
  { key: null, label: '서울 전체' },
  { key: 'HONGDAE_HAPJEONG_SANGSU_YEONNAM', label: '홍대·합정·상수·연남' },
  { key: 'GANGNAM_YEOKSAM_SEONLEUNG_SAMSUNG', label: '강남역·역삼·선릉·삼성' },
  { key: 'SINCHON_EHWA_AHYEON_YEONHUI', label: '신촌·이대·아현·연희' },
  { key: 'SINSA_NONHYEON_CHEONGDAM_APGUJEONG', label: '신사·논현·청담·압구정' },
  { key: 'MANGWON_SEONGSAN_SANGAM', label: '망원·성산·상암' },
  { key: 'SEOCHO_GYODAE_BANGBAE', label: '서초·교대·방배' },
  { key: 'MYEONGDONG_EULJIRO_DONGDAEMUNSTATION', label: '명동·을지로·동대문역' },
  { key: 'SEONGSU_WANGSIMNI_SEOULFOREST', label: '성수·왕십리·서울숲' },
  { key: 'YEONGDEUNGPO_YEOUIDO_DANGSAN_MUNRAE', label: '영등포·여의도·당산·문래' },
  { key: 'JONGNO_GWANGHWAMUN_DAEHANGNO', label: '종로·광화문·대학로' },
  { key: 'SONGPA_JAMSIL_BANGI', label: '송파·잠실·방이' },
  { key: 'YONGSAN_ITAEWON_HANNAM', label: '용산·이태원·한남' },
  { key: 'GWANAK_SILLIM_SNUSTATION', label: '관악·신림·서울대입구' },
  { key: 'GWANGJIN_KONKUK_GUUI_GUNJA', label: '광진·건대·구의·군자' },
  { key: 'DONGJAK_SADANG_ISU', label: '동작·사당·이수' },
  { key: 'SEONGBUK_SUNGSHIN_ANAM', label: '성북·성신여대·안암' },
  { key: 'GANGSEO_MAGOK_HWAGOK', label: '강서·마곡·화곡' },
  { key: 'DOGOK_DAECHI_GAECHE_SUSUEO', label: '도곡·대치·개포·수서' },
  { key: 'MAPO_GONGDEOK_DAEHEUNG', label: '마포역·공덕·대흥' },
  { key: 'GURO_SINDORIM_GOCHEOK', label: '구로·신도림·고척' },
  { key: 'GEUMCHEON_GASAN_DOKSAN', label: '금천·가산·독산' },
  { key: 'GANGDONG_SEONGNAE_CHEONHO_GILDONG', label: '강동·성내·천호·길동' },
  { key: 'DONGDAEMUNGU_CHEONGRYANGRI_HOEGI', label: '동대문구·청량리·회기' },
  { key: 'YANGCHEON_MOKDONG_SINJEONG', label: '양천·목동·신정' },
  { key: 'EUNPYEONG_BULGWANG_YEONSINNAE', label: '은평·불광·연신내' },
  { key: 'NOWON_SANGGYE_GONGLEUNG', label: '노원·상계·공릉' },
  { key: 'GANGBUK_SUYU_MIA', label: '강북·수유·미아' },
  { key: 'JUNGNANG_SANGBONG_MYEONMOK', label: '중랑·상봉·면목' },
  { key: 'DOBONG_SSANGMUN_CHANGDONG', label: '도봉·쌍문·창동' },
];
