export const REGIONS = [
  { key: 'Seoul', label: '서울', isActive: true },
  { key: 'Gyeonggi', label: '경기', isActive: false },
  { key: 'Incheon', label: '인천', isActive: false },
  { key: 'Busan', label: '부산', isActive: false },
  { key: 'Gwangju', label: '광주', isActive: false },
  { key: 'Daegu', label: '대구', isActive: false },
  { key: 'Daejeon', label: '대전', isActive: false },
  { key: 'Ulsan', label: '울산', isActive: false },
  { key: 'Jeju', label: '제주', isActive: false },
  { key: 'Gangwon', label: '강원', isActive: false },
  { key: 'Gyeongnam', label: '경남', isActive: false },
  { key: 'Gyeongbuk', label: '경북', isActive: false },
  { key: 'Jeonla', label: '전남/전북', isActive: false },
  { key: 'ChungBuk', label: '충북', isActive: false },
  { key: 'ChungnamAndSejong', label: '충남/세종', isActive: false },
];

export const AREA_FILTERS = [
  { key: null, content: '서울 전체' },
  { key: 'HONGDAE_HAPJEONG_SANGSU_YEONNAM', content: '홍대·합정·상수·연남' },
  { key: 'GANGNAM_YEOKSAM_SEONLEUNG_SAMSUNG', content: '강남역·역삼·선릉·삼성' },
  { key: 'SINCHON_EHWA_AHYEON_YEONHUI', content: '신촌·이대·아현·연희' },
  { key: 'SINSA_NONHYEON_CHEONGDAM_APGUJEONG', content: '신사·논현·청담·압구정' },
  { key: 'MANGWON_SEONGSAN_SANGAM', content: '망원·성산·상암' },
  { key: 'SEOCHO_GYODAE_BANGBAE', content: '서초·교대·방배' },
  { key: 'MYEONGDONG_EULJIRO_DONGDAEMUNSTATION', content: '명동·을지로·동대문역' },
  { key: 'SEONGSU_WANGSIMNI_SEOULFOREST', content: '성수·왕십리·서울숲' },
  { key: 'YEONGDEUNGPO_YEOUIDO_DANGSAN_MUNRAE', content: '영등포·여의도·당산·문래' },
  { key: 'JONGNO_GWANGHWAMUN_DAEHANGNO', content: '종로·광화문·대학로' },
  { key: 'SONGPA_JAMSIL_BANGI', content: '송파·잠실·방이' },
  { key: 'YONGSAN_ITAEWON_HANNAM', content: '용산·이태원·한남' },
  { key: 'GWANAK_SILLIM_SNUSTATION', content: '관악·신림·서울대입구' },
  { key: 'GWANGJIN_KONKUK_GUUI_GUNJA', content: '광진·건대·구의·군자' },
  { key: 'DONGJAK_SADANG_ISU', content: '동작·사당·이수' },
  { key: 'SEONGBUK_SUNGSHIN_ANAM', content: '성북·성신여대·안암' },
  { key: 'GANGSEO_MAGOK_HWAGOK', content: '강서·마곡·화곡' },
  { key: 'DOGOK_DAECHI_GAECHE_SUSUEO', content: '도곡·대치·개포·수서' },
  { key: 'MAPO_GONGDEOK_DAEHEUNG', content: '마포역·공덕·대흥' },
  { key: 'GURO_SINDORIM_GOCHEOK', content: '구로·신도림·고척' },
  { key: 'GEUMCHEON_GASAN_DOKSAN', content: '금천·가산·독산' },
  { key: 'GANGDONG_SEONGNAE_CHEONHO_GILDONG', content: '강동·성내·천호·길동' },
  { key: 'DONGDAEMUNGU_CHEONGRYANGRI_HOEGI', content: '동대문구·청량리·회기' },
  { key: 'YANGCHEON_MOKDONG_SINJEONG', content: '양천·목동·신정' },
  { key: 'EUNPYEONG_BULGWANG_YEONSINNAE', content: '은평·불광·연신내' },
  { key: 'NOWON_SANGGYE_GONGLEUNG', content: '노원·상계·공릉' },
  { key: 'GANGBUK_SUYU_MIA', content: '강북·수유·미아' },
  { key: 'JUNGNANG_SANGBONG_MYEONMOK', content: '중랑·상봉·면목' },
  { key: 'DOBONG_SSANGMUN_CHANGDONG', content: '도봉·쌍문·창동' },
];
